[env:native]
platform = native
test_framework = unity
build_src_filter = -<*>
test_filter = test_functional_native
build_flags =
  -Iinclude

[env:esp-wrover-kit-smoke]
platform = espressif32
board = esp-wrover-kit
framework = arduino
test_framework = unity
test_filter = test_board_smoke
test_build_src = yes
upload_protocol = esptool
build_flags =
  -D BOARD_ESP_WROVER_KIT
lib_deps =
  adafruit/Adafruit BusIO @ ^1.17.0
  adafruit/Adafruit SSD1306 @ ^2.5.1
  adafruit/Adafruit GFX Library @ ^1.10.10
  adafruit/Adafruit SHT31 Library @ ^2.2.2
